# Generated by Django 3.1 on 2020-12-15 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_auto_20201020_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('type', models.CharField(default='quiz', max_length=127)),
                ('about', models.JSONField(default=dict)),
                ('fee', models.JSONField(default=dict)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(blank=True, max_length=31, null=True)),
                ('pricing', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='save',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save', to='api.news'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='api.news'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.JSONField(default=dict)),
                ('answer', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('fee', models.IntegerField()),
                ('about', models.JSONField(default=dict)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('comp', models.ManyToManyField(blank=True, related_name='event', to='api.Comp')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('participants', models.ManyToManyField(blank=True, related_name='my_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.JSONField(default=dict)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comp',
            name='org',
            field=models.ManyToManyField(blank=True, related_name='org_quiz', to='api.Organization'),
        ),
        migrations.AddField(
            model_name='comp',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='my_quiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comp',
            name='ques',
            field=models.ManyToManyField(blank=True, to='api.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='api.organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subscriptionplan'),
        ),
    ]
