# Generated by Django 3.1.4 on 2020-12-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201215_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='api.news'),
        ),
    ]
